# -*- mode: ruby -*-
# vi: set ft=ruby :

# Vagrantfile API/syntax version. Don't touch unless you know what you're doing!
VAGRANTFILE_API_VERSION = "2"

Vagrant.configure(VAGRANTFILE_API_VERSION) do |config|

  config.vm.box = "wheezy"
  config.vm.network "private_network", ip: "192.168.207.38"
  config.vm.host_name = "printedjournals.vagrant.vm"

  config.vm.provision :shell, :inline => "apt-get update"

  config.vm.provision "puppet" do |puppet|
    puppet.manifests_path = "manifests"
    puppet.manifest_file  = "init.pp"
    puppet.module_path = ['puppet-applications/vagrant-modules', 'puppet-applications/modules', 'puppet-infrastructure/modules']
  end

end
